[package]
name = "gocd"
version = "0.1.0"
authors = ["Ilari Mäkimattila <ilari.makimattila@gmail.com>"]
homepage = "https://github.com/ilari-makimattila/gocd-rs"

[dependencies]
reqwest = "0.8.2"
serde = "1.0"
serde_derive = "1.0"
serde_json = "1.0"

[dev-dependencies]
mockito = "0.9.0"

